---
- name: 'security | borgbackup | create or update remote repository user'
  delegate_to: '{{ item.1.host }}'
  ansible.builtin.user:
    name: '{{ item.1.user }}'
    home: '{{ item.1.home | d("/var/lib/borgbackup/" + item.1.user) }}'
    createhome: true
    shell: '/bin/bash'
    state: 'present'
  loop: '{{ borgbackup_job | subelements("repository") }}'

- name: 'security | borgbackup | create ssh configuration directory'
  delegate_to: '{{ item.1.host }}'
  ansible.builtin.file:
    dest: '{{ item.1.home | d("/var/lib/borgbackup/" + item.1.user) }}/{{ item.0.name }}'
    owner: '{{ item.1.user }}'
    group: '{{ item.1.group | d(item.1.user) }}'
    mode: '0700'
    state: 'directory'
  loop: '{{ borgbackup_job | subelements("repository") }}'

- name: 'security | borgbackup | download public ssh key'
  ansible.builtin.slurp:
    src: '{{ item.0.home | d("/root") }}/.ssh/id_{{ borgbackup_ssh_key_type }}.pub'
  loop: '{{ borgbackup_job | subelements("repository") }}'
  register: borgbackup_client_pub_key

- name: 'security | borgbackup | configure ssh key at remote repository'
  delegate_to: '{{ item.1.host }}'
  ansible.posix.authorized_key:
    user: '{{ item.1.user }}'
    key: '{{ borgbackup_client_pub_key.results[borgbackup_client_pub_key_index].content | b64decode }}'
    key_options: 'restrict,command="borg serve --restrict-to-path={{ item.1.home | d("/var/lib/borgbackup/" + item.1.user) }}/{{ item.0.name }}"'
  loop: '{{ borgbackup_job | subelements("repository") }}'
  loop_control:
    index_var: borgbackup_client_pub_key_index
...
