---
- name: 'security | borgbackup | create or update remote repository user'
  delegate_to: '{{ item.1.host }}'
  ansible.builtin.user:
    name: '{{ item.1.user }}'
    home: '{{ item.1.home | d("/var/lib/borgbackup/" + item.1.user) }}'
    createhome: true
    shell: '/bin/bash'
    state: 'present'
  loop: '{{ borgbackup_job | subelements("repository") }}'

- name: 'security | borgbackup | create ssh configuration directory'
  delegate_to: '{{ item.1.host }}'
  ansible.builtin.file:
    dest: '{{ item.1.home | d("/var/lib/borgbackup/" + item.1.user) }}/{{ item.0.name }}'
    owner: '{{ item.1.user }}'
    group: '{{ item.1.group | d(item.1.user) }}'
    mode: '0700'
    state: 'directory'
  loop: '{{ borgbackup_job | subelements("repository") }}'
...
