workflow:
  rules:
  - if: $CI_COMMIT_BRANCH

stages:
- test

molecule test:
  image: mattermost/podman:1.8.0
  stage: test
  before_script:
  - apt update
  - apt install -y python3 python3-dev python3-pip gcc git curl build-essential
    autoconf automake python3-cryptography musl-dev libffi-dev libssl-dev
  - podman info
  - python3 --version
  - python3 -m pip install ansible molecule[podman] yamllint
  - ansible --version
  - molecule --version
  script:
  - make test
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
