workflow:
  rules:
  - if: $CI_COMMIT_BRANCH

stages:
- test

molecule test:
  image: python:3.10
  stage: test
  before_script:
  - apt update
  - apt install -y fuse-overlayfs podman
  - echo -e '[storage]\ndriver = "overlay"\nrunroot = "/var/obj/podman/storage"\ngraphroot = "/var/obj/podman/storage"\n[storage.options.overlay]\nmount_program = "/usr/bin/fuse-overlayfs"\nmountopt = "nodev,metacopy=on"' > /etc/containers/storage.conf
  - echo -e '[engine]\ncgroup_manager = "cgroupfs"' > /etc/containers/containers.conf
  - podman info
  - python3 --version
  - python3 -m pip install ansible ansible-lint molecule molecule-plugins[podman] yamllint
  - ansible --version
  - molecule --version
  script:
  - make test
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
