---
- name: 'security | sshd | validate conf and reload service'
  ansible.builtin.command: >
    sshd -t -f /etc/ssh/sshd_config
  notify:
  - 'security | sshd | reload service'
  changed_when: true
  tags: [ 'role:sshd', 'task::reload', 'role::sshd:reload' ]

- name: 'security | sshd | validate conf and restart service'
  ansible.builtin.command: >
    sshd -t -f /etc/ssh/sshd_config
  notify:
  - 'security | sshd | restart service'
  changed_when: true
  tags: [ 'role::sshd', 'task::restart', 'role::sshd:restart' ]

- name: 'security | sshd | reload service'
  ansible.builtin.service:
    name: '{{ sshd_service_name }}'
    state: 'reloaded'
  tags: [ 'role:sshd', 'task::reload', 'role::sshd:reload' ]

- name: 'security | sshd | restart service'
  ansible.builtin.service:
    name: '{{ sshd_service_name }}'
    state: 'restarted'
  tags: [ 'role::sshd', 'task::restart', 'role::sshd:restart' ]
