---
- name: "security | sshd | reload"
  ansible.builtin.service:
    name: "{{ sshd__service_name }}"
    state: "reloaded"

- name: "security | sshd | restart"
  ansible.builtin.service:
    name: "{{ sshd__service_name }}"
    state: "restarted"
  when:
  - "sshd__ansible_restart | bool"
