---
- name: "security | sshd | reload service"
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: "reloaded"

- name: "security | sshd | restart service"
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: "restarted"
  when:
  - "sshd_ansible_restart | bool"
