---
dependencies: []

galaxy_info:
  author: havlas.me
  description: An Ansible role to install and configure the firewall using nftables on Debian and Ubuntu running systemd.
  company: havlas.me
  issue_tracker_url: https://gitlab.com/havlas.me/ansible-collection-security/-/issues
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
  - linux
  - security
  - firewall
  - nftables
  - netfilter
