---
# the sshd package name
sshd__package_name: "openssh-server"
# the sshd service name
sshd__service_name: "sshd"

# the sshd keygen command
sshd__keygen:
  ecdsa: "/usr/bin/ssh-keygen -q -N '' -t ecdsa -f {{ sshd__conf | dirname }}/ssh_host_ed25519_key"
  ed25519: "/usr/bin/ssh-keygen -q -N '' -t ed25519 -f {{ sshd__conf | dirname }}/ssh_host_ed25519_key"
  rsa: "/usr/bin/ssh-keygen -q -N '' -t rsa -b 4096 -f {{ sshd__conf | dirname }}/ssh_host_ed25519_key"
