---
# borgbackup package state ('present', 'latest', 'absent')
# * 'present' ensures that the package is installed
# * 'latest' ensures that the latest version of the package is installed
# * 'absent' ensures that the package is not installed
borgbackup__state: 'present'
# should start the borgbackup service at boot? (using systemd)
borgbackup__enabled: true
# can ansible reload the borgbackup service? (using systemd)
borgbackup__ansible_reload: true
# can ansible restart the borgbackup service? (using systemd)
borgbackup__ansible_restart: true

# borgbackup service dedicated user
borgbackup__user: 'root'
# borgbackup service dedicated group
borgbackup__group: '{{ borgbackup__user }}'
# borgbackup service working directory
borgbackup__home: '/root'

# borgbackup job list
## - name: string
##   passphrase: string
##   encryption: string | d('repokey')
##   repository: dict[]
##   - host: string
##     user: string
##     home: string
##     group: string | d(item.user)
##     append_only: boolean | d(false)
##     host_pub_key: string | d(omit)
##     management: dict | d(omit)
##       host: string
##       user: string | d('root')
##       home: string | d(omit)
##       group: string | d(item.user)
##     state: enum('present', 'absent') | d('present')
##   template: string | d(borgbackup_job_template)
##   state: enum('present', 'absent') | d('present')
borgbackup_job: []
# the borgbackup job default template
borgbackup_job_template: 'etc/borgbackup/__default__.yaml.j2'
# the borgbackup job.d directory
borgbackup_job_d: '/etc/borgbackup'
# the borgbackup ssh key type
borgbackup_ssh_key_type: 'ed25519'

# the borgbackup management job default template
borgbackup_management_template: '{{ borgbackup_job_template }}'
# the borgbackup management.d directory
borgbackup_management_d: '/etc/borgbackup/management.d'
# the borgbackup management ssh key type
borgbackup_management_ssh_key_type: '{{ borgbackup_ssh_key_type }}'

# the borgbackup service option
borgbackup_service_option: '--config {{ borgbackup_job_d | quote }} --verbosity -1 --syslog-verbosity 1'
...
