---
# the borgbackup package state ('present', 'latest')
borgbackup_state: 'present'
# should start the borgbackup service at boot
borgbackup_enabled: true

# the borgbackup dedicated user
borgbackup_user: 'root'
# the borgbackup dedicated group
borgbackup_group: '{{ borgbackup_user }}'
# the borgbackup dedicated home directory
borgbackup_home: '/root'

# the borgbackup job list
## - name: string
##   passphrase: string
##   encryption: string | d('repokey')
##   repository: dict[]
##   - host: string
##     user: string
##     home: string
##     group: string | d(item.user)
##     append_only: boolean | d(false)
##     host_pub_key: string | d(omit)
##     management: dict | d(omit)
##       host: string
##       user: string | d('root')
##       home: string | d(omit)
##       group: string | d(item.user)
##     state: enum('present', 'absent') | d('present')
##   template: string | d(borgbackup_job_template)
##   state: enum('present', 'absent') | d('present')
borgbackup_job: []
# the borgbackup job default template
borgbackup_job_template: 'etc/borgbackup/__default__.yaml.j2'
# the borgbackup job.d directory
borgbackup_job_d: '/etc/borgbackup'
# the borgbackup ssh key type
borgbackup_ssh_key_type: 'ed25519'

# the borgbackup management job default template
borgbackup_management_template: '{{ borgbackup_job_template }}'
# the borgbackup management.d directory
borgbackup_management_d: '/etc/borgbackup/management.d'
# the borgbackup management ssh key type
borgbackup_management_ssh_key_type: '{{ borgbackup_ssh_key_type }}'

# the borgbackup service option
borgbackup_service_option: '--config {{ borgbackup_job_d | quote }} --verbosity -1 --syslog-verbosity 1'
...
