---
- name: 'Assert that the Molly-Guard State Value is Valid'
  ansible.builtin.assert:
    that:
    - molly_guard__state in [ 'present', 'latest', 'absent' ]
    msg: 'The molly_guard__state must be one of [ "present", "latest", "absent" ] - "{{ molly_guard__state }}" is not supported'
    quiet: true
  tags: [ 'always' ]

#
# Install
#

- name: 'Install | {{ molly_guard__state | replace("present", "Install") | replace("latest", "Update") | replace("absent", "Uninstall") }} the Molly-Guard via APT'
  ansible.builtin.apt:
    name: '{{ molly_guard__package_name }}'
    update_cache: '{{ molly_guard__state != "absent" }}'
    cache_valid_time: 1800
    state: '{{ molly_guard__state }}'
  tags: [ 'role:molly_guard', 'role:molly_guard:install', 'task:install' ]
...
