---
- name: 'Security | Molly-Guard | Include Distro-Specific Variables'
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role::molly_guard', 'task::install', 'role::molly_guard::install' ]
...
