---
- name: 'Load Distribution-Specific Variables'
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'preflight.yml'
  tags: [ 'always' ]
- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role::molly_guard', 'role::molly_guard::install', 'task::install' ]
...
