---
- name: 'Assert that the Managed Node OS is Supported'
  ansible.builtin.assert:
    that:
    - (ansible_distribution|lower == "debian" and ansible_distribution_version|int in [10, 11, 12]) or
      (ansible_distribution|lower == "ubuntu" and ansible_distribution_version|int in [20, 22, 24])
    msg: 'The "{{ ansible_distribution }} {{ ansible_distribution_version }}" is not supported'
    quiet: true

- name: 'Assert that the Molly-Guard State Value is Valid'
  ansible.builtin.assert:
    that:
    - molly_guard_state in [ 'present', 'latest', 'absent' ]
    msg: 'The molly_guard_state must be in [ "present", "latest", "absent" ]'
    quiet: true
  tags: [ 'always' ]

#
# Install
#

- name: 'Install | {{ (molly_guard_state == "absent") | ternary("Uninstall", "Install or Update") }} the Molly-Guard via APT'
  ansible.builtin.apt:
    name: '{{ molly_guard_package_name }}'
    update_cache: '{{ molly_guard_state != "absent" }}'
    cache_valid_time: 1800
    state: '{{ molly_guard_state }}'
  tags: [ 'role:molly_guard', 'role:molly_guard:install', 'task:install' ]
...
