---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
- name: security-molly_guard-debian
  image: docker.io/library/python:3.10
  pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
