---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
- name: security-molly_guard-debian-bullseye
  image: docker.io/library/python:3.10-bullseye
  pre_build_image: true
- name: security-molly_guard-debian-bookworm
  image: docker.io/library/python:3.10-bookworm
  pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
