---
- name: "(security.borgmatic) configure borgmatic job"
  ansible.builtin.template:
    dest: "{{ borgmatic_confdir }}/{{ item.name | mandatory }}.yaml"
    src: "{{ item.src | default(borgmatic_job_template) }}"
    owner: "root"
    group: "root"
    mode: "0600"
    force: "yes"
  loop: "{{ borgmatic_job }}"
