---
- name: "(security.borgmatic) remove borgmatic job"
  ansible.builtin.file:
    name: "{{ item.borgmatic_file | d(borgmatic_confdir + '/' + (item.name | mandatory) + '.yaml') }}"
    state: "absent"
  loop: "{{ borgmatic_job }}"
  when: "item.state | d('present') == 'absent'"

- name: "(security.borgmatic) create, or update borgmatic job"
  ansible.builtin.template:
    dest: "{{ item.borgmatic_file | d(borgmatic_confdir + '/' + (item.name | mandatory) + '.yaml') }}"
    src: "{{ item.template | d(item.src | d(borgmatic_job_tmpl)) }}"
    owner: "root"
    group: "root"
    mode: "0600"
    force: "yes"
  loop: "{{ borgmatic_job }}"
  when: "item.state | d('present') == 'present'"
