---
- name: "(security.borgmatic) install dependency package"
  ansible.builtin.package:
    name:
    - "borgbackup"
    - "python3-pip"
    state: "present"
  when: "borgmatic_state != 'absent'"

- name: "(security.borgmatic) install borgmatic package"
  ansible.builtin.pip:
    name: "{{ borgmatic_package }}"
    state: "{{ borgmatic_state }}"

- name: "(security.borgmatic) create directory structure"
  ansible.builtin.file:
    name: "{{ borgmatic_confdir }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  when: "borgmatic_state != 'absent'"
