---
# the sshd package state ('present', 'latest')
sshd__state: "present"
# should start the sshd service at boot
sshd__enabled: "yes"
# can ansible restart the sshd service
sshd__ansible_restart: "yes"

# the sshd port
sshd__port: [ "22" ]
# the sshd listen
#sshd__listen: [ "0.0.0.0" ]
# the ssh host key type
#sshd__host_key_type: [ "rsa", "ecdsa", "ed25519" ]

# the sshd conf file
sshd__conf_file: "/etc/ssh/sshd_config"
# the sshd conf template
sshd__conf_template: "sshd_config.j2"
# the sshd conf dot-d directory
sshd__conf_d: "/etc/ssh/sshd_config.d"
# the sshd conf dot-d file list
sshd__conf_d_file: []

# the sshd moduli file
sshd__moduli_file: "/etc/ssh/moduli"
# the sshd moduli minimal length
sshd__moduli_min: 3071

# the sshd issue file
sshd__issue_file: "/etc/issue.net"
# the sshd issue template
#sshd__issue_template: "issue.net.j2"
