---
# the sshd package state ('present', 'latest')
sshd_state: 'present'
# should the sshd service start at boot
sshd_enabled: true

# the sshd port
sshd_port: [ '22' ]
# the sshd listen ip
#sshd_listen: [ '0.0.0.0' ]
# the ssh host key type
#sshd_host_key_type: [ 'ed25519', 'rsa', 'ecdsa' ]

# the sshd conf list
## - dest: string
##   src: string | d(sshd_conf_template)
##   state: enum('present', 'absent') | d('present')
sshd_conf:
- dest: '/etc/ssh/sshd_config'
  src: 'etc/ssh/sshd_config.j2'
## basic password or pubkey authentication
- dest: '20-password-authentication.conf'
  src: 'etc/ssh/sshd_config.d/authentication.conf.j2'
## allow client to set the locale environment variables
- dest: '40-accept-env-locale-only.conf'
  src: 'etc/ssh/sshd_config.d/accept-env.conf.j2'
  sshd_accept_env: 'LANG LC_*'
# the sshd conf.d default template
sshd_conf_template: 'etc/ssh/sshd_config.d/__default__.conf.j2'
# the sshd conf.d directory
sshd_conf_d: '/etc/ssh/sshd_config.d'

# the sshd moduli file
sshd_moduli_file: '/etc/ssh/moduli'
# the sshd moduli minimal size
#sshd_moduli_minsize: 3071
