---
# the sshd package state ('present', 'latest')
sshd__state: "present"
# should start the sshd service at boot
sshd__service_enabled: "yes"
# can ansible restart the sshd service
sshd__can_restart: "yes"

# the sshd port
sshd__port: "22"
# the sshd listen
#sshd__listen: "0.0.0.0"

# the sshd conf file
sshd__conf: "{{ sshd__confdir }}/sshd_config"
# the sshd conf template
sshd__conf_tmpl: "sshd_config.j2"
# the sshd conf include directory
sshd__conf_includedir: "{{ sshd__confdir }}/sshd_config.d"

# password authentication ('yes', 'no')
sshd__password_authentication: "yes"
# permit root login ('yes', 'no', 'prohibit-password')
sshd__permit_root_login: "prohibit-password"

# the sshd conf directory
sshd__confdir: "/etc/ssh"
