---
# the sshd package state ('present', 'latest') - 'absent' is not supported
sshd__state: 'present'
# should the sshd service start at boot
sshd__enabled: true
# can ansible reload sshd service?
sshd__ansible_reload: true
# can ansible restart sshd service?
sshd__ansible_restart: true

# the sshd listen port
sshd__port: [ '22' ]
# the sshd listen ip
#sshd__listen_to: [ '0.0.0.0' ]
# the ssh host key type
#sshd__host_key_type: [ 'ed25519', 'rsa', 'ecdsa' ]

# the sshd conf list
## - dest: string
##   tmpl: string | d(sshd__conf_template)
##   state: enum('present', 'absent') | d('present')
sshd__conf:
- dest: 'sshd_config'
  tmpl: 'etc/ssh/sshd_config.j2'
- dest: 'sshd_config.d/20-default-daemon.conf'
  content: |-
    PrintMotd no
    PrintLastLog yes
    AcceptEnv {{ sshd__accept_env | d('LANG LC_*') }}
- dest: 'sshd_config.d/40-default-authentication.conf'
  content: |-
    PubkeyAuthentication yes
    PasswordAuthentication yes
    KbdInteractiveAuthentication no
    UsePAM yes
    PermitRootLogin {{ sshd__permit_root_login | d('prohibit-password') }}
# the sshd conf default template
sshd__conf_template: '[content].j2'
# the sshd conf directory
sshd__confdir: '/etc/ssh'

# the sshd moduli file
sshd__moduli_file: '/etc/ssh/moduli'
# the sshd moduli minimal size
#sshd__moduli_minsize: 3071
...
