---
# the sshd package state ('present', 'latest')
sshd__state: "present"
# should start the sshd service at boot
sshd__enabled: "yes"
# can ansible restart the sshd service
sshd__ansible_restart: "yes"

# the sshd port
sshd__port: [ "22" ]
# the sshd listen
#sshd__listen: [ "0.0.0.0" ]
# the ssh host key type
#sshd__host_key_type: [ "rsa", "ecdsa", "ed25519" ]

# the sshd conf file
sshd__conf: "/etc/ssh/sshd_config"
# the sshd conf template
sshd__conf_template: "sshd_config.j2"
# the sshd conf dot-d directory
sshd__conf_d: "/etc/ssh/sshd_config.d"
