---
- name: "(security.nftables) manage nftables main configuration"
  ansible.builtin.template:
    src: "{{ nftables_conf_template }}"
    dest: "{{ nftables_conf }}"
    owner: "root"
    group: "root"
    mode: "0755"
    force: "yes"
  notify: "(security.nftables) reload service"

- name: "(security.nftables) remove nftables configuration"
  ansible.builtin.file:
    name: "{{ nftables_confd }}/{{ item.dest | mandatory }}"
    state: "absent"
  loop: "{{ nftables_ruleset }}"
  when: "item.state | d('present') == 'absent'"
  notify: "(security.nftables) reload service"

- name: "(security.nftables) create, or update nftables configuration"
  ansible.builtin.template:
    dest: "{{ nftables_confd }}/{{ item.dest | mandatory }}"
    src: "{{ item.src | default('ruleset.conf.j2') }}"
    owner: "root"
    group: "root"
    mode: "0644"
    force: "yes"
  loop: "{{ nftables_ruleset }}"
  when: "item.state | d('present') == 'present'"
  notify: "(security.nftables) reload service"
