---
- ansible.builtin.import_tasks: 'configure/d.yml'

- name: 'security | nftables | create or update configuration file'
  ansible.builtin.template:
    dest: '{{ nftables_conf_file }}'
    src: '{{ nftables_conf_template }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
  - 'security | nftables | reload service'
  when:
  - nftables_conf_template is defined
