---
- name: 'Security | nftables | Delete Configuration File'
  ansible.builtin.file:
    name: '{{ item.dest | mandatory | havlasme.security.abspath(nftables_conf_d) }}'
    state: 'absent'
  loop: '{{ nftables_conf | selectattr("state", "havlasme.security.is_absent") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'Security | nftables | Reload Service'
  when:
  - nftables_state != 'absent'

- name: 'Security | nftables | Create or Update Configuration File'
  ansible.builtin.template:
    dest: '{{ item.dest | mandatory | havlasme.security.abspath(nftables_conf_d) }}'
    src: '{{ item.tmpl | d(nftables_conf_template) }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ nftables_conf | selectattr("state", "havlasme.security.is_present") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'Security | nftables | Reload Service'
  when:
  - nftables_state != 'absent'
...
