---
- name: 'Install | {{ (nftables__state | replace("present", "Install") | replace("latest", "Update") | replace("absent", "Uninstall" }} the NFTables via APT'
  ansible.builtin.apt:
    name: '{{ nftables__package_name }}'
    update_cache: '{{ nftables__state != "absent" }}'
    cache_valid_time: 1800
    state: '{{ nftables__state }}'
  notify:
  - 'NFTables | Validate Conf and Restart Service'
...
