---
- name: 'Install | {{ (nftables_state == "absent") | ternary("Uninstall", "Install or Update") }} the NFTables via APT'
  ansible.builtin.apt:
    name: '{{ nftables_package_name }}'
    update_cache: '{{ nftables_state != "absent" }}'
    cache_valid_time: 1800
    state: '{{ nftables_state }}'
  notify:
  - 'NFTables | Validate Conf and Restart Service'

- name: 'Install | Create the NFTables Conf Directory Structure'
  ansible.builtin.file:
    name: '{{ nftables_confdir }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  notify:
  - 'NFTables | Validate Conf and Reload Service'
  when:
  - nftables_state != 'absent'
...
