---
- name: 'Install | {{ (nftables_state == "absent") | ternary("Uninstall", "Install or Update") }} the NFTables Package via APT'
  ansible.builtin.apt:
    name: '{{ nftables_package_name }}'
    state: '{{ nftables_state }}'
  notify:
  - 'Security | NFTables | Restart Service'

- name: 'Security | NFTables | Install | Create the NFTables Conf Directory Structure'
  ansible.builtin.file:
    name: '{{ nftables_conf_d }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  notify:
  - 'Security | NFTables | Reload Service'
  when:
  - nftables_state != 'absent'
...
