---
- name: 'Assert that the NFTables State Value is Valid'
  ansible.builtin.assert:
    that:
    - nftables__state in [ 'present', 'latest', 'absent' ]
    msg: 'The `nftables__state` must be one of [ "present", "latest", "absent" ] - "{{ nftables__state }}" is not supported'
    quiet: true
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role:nftables', 'role:nftables:install', 'task:install' ]
- ansible.builtin.import_tasks: 'configure.yml'
  tags: [ 'role:nftables', 'role:nftables:configure', 'task:configure' ]
- ansible.builtin.import_tasks: 'service.yml'
  tags: [ 'role:nftables', 'role:nftables:service', 'task:service' ]
...
