---
- name: 'Service | {{ (nftables_state == "absent") | ternary("Stop and Disable", "Start and Enable") }} the NFTables Service'
  ansible.builtin.systemd:
    name: '{{ nftables_service_name }}'
    daemon_reload: true
    enabled: '{{ (nftables_state == "absent") | ternary("no", nftables_enabled) }}'
    state: '{{ (nftables_state == "absent") | ternary("stopped", "started") }}'
...
