---
- name: 'Service | {{ (nftables__state == "absent") | ternary("Stop and Disable", "Start and Enable") }} the NFTables Service'
  ansible.builtin.systemd:
    name: '{{ nftables__service_name }}'
    daemon_reload: true
    enabled: '{{ (nftables__state == "absent") | ternary("no", nftables__enabled) }}'
    state: '{{ (nftables__state == "absent") | ternary("stopped", "started") }}'
...
