---
- name: 'security | borgbackup | create or update local user'
  ansible.builtin.user:
    name: '{{ item.user | d("borgbackup") }}'
    home: '{{ item.home | d("/var/lib/borgbackup") }}'
    createhome: true
    shell: '/usr/sbin/nologin'
    system: true
    state: '{{ borgbackup_state }}'
  loop: '{{ borgbackup_job }}'
  when:
  - item.user | d('borgbackup') != 'root'

- name: 'security | borgbackup | TODO'
  ansible.builtin.file:
    dest: '{{ item.home | d("/var/lib/borgbackup") }}/.ssh'
    owner: '{{ item.user | d("borgbackup") }}'
    group: '{{ item.group | d(item.user) | d("borgbackup") }}'
    mode: '0700'
    state: 'directory'
  loop: '{{ borgbackup_job }}'

- name: 'security | borgbackup | create ssh key'
  community.crypto.openssh_keypair:
    path: '{{ item.home | d("/var/lib/borgbackup") }}/.ssh/id_ed25519'
    owner: '{{ item.user | d("borgbackup") }}'
    group: '{{ item.group | d(item.user) | d("borgbackup") }}'
    mode: '0600'
    type: 'ed25519'
  loop: '{{ borgbackup_job }}'

- name: 'security | borgbackup | TODO'
  community.general.sudoers:
    name: 'borgbackup'
    user: '{{ item.user | d("borgbackup") }}'
    nopassword: true
    commands:
    - '/usr/bin/borg'
    - '/usr/bin/borgmatic -c "{{ item.borgbackup_file | d(borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml") }}"'
    state: 'present'
  loop: '{{ borgbackup_job }}'

- name: 'security | borgbackup | delete backup job'
  ansible.builtin.file:
    dest: '{{ item.borgbackup_file | d(borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml") }}'
    state: 'absent'
  loop: '{{ borgbackup_job | selectattr("state", "havlasme.security.is_absent") | list }}'

- name: 'security | borgbackup | create or update backup job'
  ansible.builtin.template:
    dest: '{{ item.borgbackup_file | d(borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml") }}'
    src: '{{ item.template | d(borgbackup_job_template) }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop: '{{ borgbackup_job | selectattr("state", "havlasme.security.is_present") | list }}'

- name: "(security.borgmatic) manage borgbackup repository host public key"
  ansible.builtin.known_hosts:
    host: "{{ item.1.host | mandatory }}"
    key: "{{ item.1.host | mandatory }} {{ item.1.host_pub_key | mandatory }}"
    hash_host: true
  loop: '{{ borgbackup_job | subelements("repository") }}'


- import_tasks: "configure/repository.yml"

- name: 'security | borgbackup | TODO 5'
  ansible.builtin.shell: |
    borgmatic -c '{{ item.borgbackup_file | d(borgbackup_job_d + "/" + (item.0.name | mandatory) + ".yaml") }}' init --encryption={{ item.1.encryption | d("repokey") }}
  loop: '{{ borgbackup_job | subelements("repository") }}'
  register: borgbackup_init
  changed_when: borgbackup_init.rc == 0 and borgbackup_init.stderr | length > 0
