---
- name: 'security | borgbackup | configure | create borgbackup client group'
  ansible.builtin.group:
    name: '{{ borgbackup_group }}'
    system: true
  when:
  - borgbackup_group != 'root'

- name: 'security | borgbackup | configure | create borgbackup client user'
  ansible.builtin.user:
    name: '{{ borgbackup_user }}'
    home: '{{ borgbackup_home }}'
    createhome: true
    group: '{{ borgbackup_group }}'
    shell: '/usr/sbin/nologin'
    system: true
  when:
  - borgbackup_user != 'root'

- name: 'security | borgbackup | configure | create borgbackup client ssh configuration directory'
  ansible.builtin.file:
    dest: '{{ borgbackup_home }}/.ssh'
    owner: '{{ borgbackup_user }}'
    group: '{{ borgbackup_group }}'
    mode: '0700'
    state: 'directory'

- name: 'security | borgbackup | configure | generate borgbackup client ssh key'
  community.crypto.openssh_keypair:
    path: '{{ borgbackup_home }}/.ssh/id_{{ borgbackup_ssh_key_type }}'
    owner: '{{ borgbackup_user }}'
    group: '{{ borgbackup_group }}'
    mode: '0600'
    type: '{{ borgbackup_ssh_key_type }}'

- name: 'security | borgbackup | configure | add repository host key to known host list'
  ansible.builtin.known_hosts:
    host: '{{ item.1.host | mandatory }}'
    key: '{{ item.1.host | mandatory }} {{ item.1.host_pub_key | mandatory }}'
    hash_host: true
  loop: '{{ borgbackup_job | subelements("repository") 
    | selectattr("0.state", "havlasme.security.is_present") | list
    | selectattr("1.state", "havlasme.security.is_present") | list }}'
  loop_control:
    label: '{{ item.1.host | mandatory }}'

- name: 'security | borgbackup | configure | delete borgbackup job configuration'
  ansible.builtin.file:
    dest: '{{ borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml" }}'
    state: 'absent'
  loop: '{{ borgbackup_job | selectattr("state", "havlasme.security.is_absent") | list }}'
  loop_control:
    label: '{{ borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml" }}'

- name: 'security | borgbackup | configure | create or update borgbackup job configuration'
  ansible.builtin.template:
    dest: '{{ borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml" }}'
    src: '{{ item.template | d(borgbackup_job_template) }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop: '{{ borgbackup_job | selectattr("state", "havlasme.security.is_present") | list }}'
  loop_control:
    label: '{{ borgbackup_job_d + "/" + (item.name | mandatory) + ".yaml" }}'

- name: 'security | borgbackup | download public ssh key'
  ansible.builtin.slurp:
    src: '{{ item.0.home | d("/root") }}/.ssh/id_{{ borgbackup_ssh_key_type }}.pub'
  loop: '{{ borgbackup_job | subelements("repository") }}'
  register: borgbackup_client_pub_key

- name: 'security | borgbackup | configure ssh key at remote repository'
  delegate_to: '{{ item.1.host }}'
  ansible.posix.authorized_key:
    user: '{{ item.1.user }}'
    key: '{{ borgbackup_client_pub_key.results[borgbackup_client_pub_key_index].content | b64decode }}'
    key_options: 'restrict,command="borg serve {% if item.1.append_only | d(false) | bool %}--append-only {% endif %}--restrict-to-path={{ item.1.home | d("/var/lib/borgbackup/" + item.1.user) }}/{{ item.0.name }}"'
  loop: '{{ borgbackup_job | subelements("repository") }}'
  loop_control:
    index_var: borgbackup_client_pub_key_index

- name: 'security | borgbackup | initialize backup repository'
  ansible.builtin.command: |
    borgmatic init
    --config '{{ borgbackup_job_d + "/" + (item.0.name | mandatory) + ".yaml" }}'
    --encryption={{ item.1.encryption | d("repokey") }}
  loop: '{{ borgbackup_job | subelements("repository") }}'
  register: borgbackup_init
  changed_when: borgbackup_init.rc == 0 and borgbackup_init.stderr | length > 0

- ansible.builtin.import_tasks: 'configure/management.yml'
...
