---
- name: 'security | borgbackup | install or update package via apt'
  ansible.builtin.apt:
    name: '{{ borgbackup_package_name }}'
    state: '{{ borgbackup_state }}'

- name: 'security | borgbackup | create directory structure'
  ansible.builtin.file:
    dest: '{{ borgbackup_job_d }}'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'
  when:
  - borgbackup_job | length > 0
...
