---
- name: "(security.borgbackup) install borgbackup package"
  ansible.builtin.package:
    name: "{{ borgbackup_package }}"
    state: "{{ borgbackup_state }}"

- name: "(security.borgbackup) create directory structure"
  ansible.builtin.file:
    name: "{{ borgbackup_datadir }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  when: "borgbackup_state != 'absent'"
