---
- name: 'Install | {{ (borgbackup__state == "absent") | ternary("Uninstall", "Install or Update") }} the BorgBackup via APT'
  ansible.builtin.apt:
    name: '{{ borgbackup__package_name }}'
    update_cache: '{{ nftables__state != "absent" }}'
    cache_valid_time: 1800
    state: '{{ borgbackup__state }}'

- name: 'Install | create borgbackup configuration directory structure'
  ansible.builtin.file:
    dest: '{{ borgbackup_job_d }}'
    owner: '{{ borgbackup_user }}'
    group: '{{ borgbackup_group }}'
    mode: '0700'
    state: 'directory'

- name: 'Install | create borgbackup systemd service unit'
  ansible.builtin.template:
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
  - dest: '/etc/systemd/system/{{ borgbackup_service_name | regex_replace("\.timer$", ".service") }}'
    src: 'etc/systemd/system/borgbackup.service.j2'
  - dest: '/etc/systemd/system/{{ borgbackup_service_name }}'
    src: 'etc/systemd/system/borgbackup.timer.j2'
  - dest: '/etc/default/{{ borgbackup_service_name | regex_replace("\.timer$", "") }}'
    src: 'etc/default/borgbackup.j2'
  loop_control:
    label: '{{ item.dest }}'
...
