---
- name: 'security | borgbackup | install | install or update borgbackup package via apt'
  ansible.builtin.apt:
    name: '{{ borgbackup_package_name }}'
    state: '{{ borgbackup_state }}'

- name: 'security | borgbackup | install | create configuration directory structure'
  ansible.builtin.file:
    dest: '{{ borgbackup_job_d }}'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'

- name: 'security | borgbackup | install | create borgbackup systemd service unit'
  ansible.builtin.template:
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
  - dest: '/etc/systemd/system/{{ borgbackup_service_name | regex_replace("\.timer$", ".service") }}'
    src: 'etc/systemd/system/borgbackup.service.j2'
  - dest: '/etc/systemd/system/{{ borgbackup_service_name }}'
    src: 'etc/systemd/system/borgbackup.timer.j2'
  - dest: '/etc/default/{{ borgbackup_service_name | regex_replace("\.timer$", "") }}'
    src: 'etc/default/borgbackup.j2'
  loop_control:
    label: '{{ item.dest }}'
...
