---
- name: 'security | borgbackup | include distribution-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role::borgbackup', 'task::install' ]
- ansible.builtin.import_tasks: 'configure.yml'
  tags: [ 'role::borgbackup', 'task::configure' ]
- ansible.builtin.import_tasks: 'service.yml'
  tags: [ 'role::borgbackup', 'task::service' ]
...
