---
- name: 'security | borgbackup | include distribution-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role::borgbackup', 'task::install', 'role::borgbackup:install' ]
- ansible.builtin.import_tasks: 'repository.yml'
  tags: [ 'role::borgbackup', 'task::configure', 'role::borgbackup:configure', 'role::borgbackup:repository' ]
- ansible.builtin.import_tasks: 'configure.yml'
  tags: [ 'role::borgbackup', 'task::configure', 'role::borgbackup:configure' ]
- ansible.builtin.import_tasks: 'management.yml'
  tags: [ 'role::borgbackup', 'task::configure', 'role::borgbackup:configure', 'role::borgbackup:management' ]
- ansible.builtin.import_tasks: 'service.yml'
  tags: [ 'role::borgbackup', 'task::service', 'role::borgbackup:service' ]
...
