---
- name: "(security.borgbackup) manage repository user"
  include_role:
    name: "havlasme.linux.user"
  vars:
    linux_user:
    - name: "{{ repository.name | mandatory }}"
      comment: "{{ repository.comment | default('borgbackup-' + (repository.name | mandatory)) }}"
      home: "{{ repository.storage | default(borgbackup_datadir + (repository.name | mandatory)) }}"
      shell: "/bin/bash"
      state: "{{ repository.state | default('present') }}"
      authorized_key:
      - key: "{{ repository.key | default(lookup('file', (repository.name | mandatory) + '/id_ssh.pub')) }}"
        key_options: 'restrict,command="borg serve --restrict-to-path={{ repository.storage | default(borgbackup_datadir + (repository.name | mandatory)) }}"'
        comment: "{{ repository.comment | default(repository.name | mandatory) }}"
  loop: "{{ borgbackup_repository }}"
  loop_control:
    loop_var: "repository"
