---
- name: 'security | borgbackup | start and enable borgbackup service'
  ansible.builtin.service:
    name: '{{ borgbackup_service_name }}'
    enabled: '{{ borgbackup_enabled }}'
    state: 'started'
...
