---
- name: 'Service | Mask the Service Provided by the BorgMatic to Avoid Conflicts'
  ansible.builtin.systemd:
    name: 'borgmatic.timer'
    enabled: false
    masked: true
    state: 'stopped'
  when:
  - borgbackup__state == 'absent'

- name: 'Service | {{ (borgbackup__state == "absent") | ternary("Stop and Disable", "Start and Enable") }} the BorgBackup Service'
  ansible.builtin.systemd:
    name: '{{ borgbackup__service_name | replace(".service", ".timer") }}'
    daemon_reload: true
    enabled: '{{ (borgbackup__state == "absent") | ternary(false, borgbackup__enabled) }}'
    state: '{{ (borgbackup__state == "absent") | ternary("stopped", "started") }}'
...
