---
- name: "(security.ssh_key) remove ssh key"
  ansible.builtin.file:
    dest: "{{ item.dest | mandatory }}"
    state: "absent"
  loop: "{{ ssh_key }}"
  when: "item.state | d('present') == 'absent'"

- name: "(security.ssh_key) create, or update ssh key"
  ansible.builtin.copy:
    dest: "{{ item.dest | mandatory }}"
    src: "{{ item.src | mandatory }}"
    owner: "root"
    group: "root"
    mode: "0600"
  loop: "{{ ssh_key }}"
  when: "item.state | d('present') == 'present'"
