---
# the nftables package state ('present', 'latest', 'absent')
nftables__state: 'present'
# should start the nftables service at boot
nftables__enabled: '{{ nftables__state != "absent" }}'
# can ansible reload nftables service?
nftables__ansible_reload: true
# can ansible restart nftables service?
nftables__ansible_restart: true

# the nftables conf list
## - dest: string
##   tmpl: string | d(nftables__conf_template)
##   state: enum('present', 'absent') | d('present')
nftables__conf:
- dest: '/etc/nftables.conf'
  tmpl: 'etc/nftables.conf.j2'
# the nftables conf default template
nftables__conf_template: '[content].j2'
# the nftables conf directory
nftables__confdir: '/etc/nftables.d'
...
