---
# the nftables package state ('present', 'latest', 'absent')
nftables_state: 'present'
# should start the nftables service at boot
nftables_enabled: true
# can ansible reload nftables service?
nftables_ansible_reload: true
# can ansible restart nftables service?
nftables_ansible_restart: true

# the nftables conf list
## - dest: string
##   src: string | d(nftables_conf_template)
##   state: enum('present', 'absent') | d('present')
## * etc/nftables.d/simple-stateful-firewall.conf.j2
##   nftables_accept_ping: boolean | d(true)
##   nftables_accept_multicast: boolean | d(false)
##   nftables_ssh_port: int | d(22)
nftables_conf:
- dest: '/etc/nftables.conf'
  src: 'etc/nftables.conf.j2'
# the nftables conf default template
nftables_conf_template: 'etc/nftables.d/__default__.conf.j2'
# the nftables conf.d directory
nftables_conf_d: '/etc/nftables.d'
...
