---
- name: "(security.nftables) reload service"
  ansible.builtin.systemd:
    name: "{{ nftables_service | mandatory }}"
    daemon_reload: "yes"
    state: "reloaded"
  tags: ["nftables", "service"]

- name: "(security.nftables) restart service"
  ansible.builtin.systemd:
    name: "{{ nftables_service | mandatory }}"
    daemon_reload: "yes"
    state: "restarted"
  tags: ["nftables", "service"]
