---
- name: "(security.nftables) reload service"
  ansible.builtin.service:
    name: "{{ nftables_service | mandatory }}"
    state: "reloaded"

- name: "(security.nftables) restart service"
  ansible.builtin.service:
    name: "{{ nftables_service | mandatory }}"
    state: "restarted"
