---
- name: 'Security | nftables | Reload Service'
  ansible.builtin.service:
    name: '{{ nftables_service_name }}'
    state: 'reloaded'
  when:
  - nftables_ansible_reload | bool
  tags: [ 'always' ]

- name: 'Security | nftables | Restart Service'
  ansible.builtin.service:
    name: '{{ nftables_service_name }}'
    state: 'restarted'
  when:
  - nftables_ansible_restart | bool
  tags: [ 'always' ]
...
