---
- name: 'Security | NFTables | Reload Service'
  ansible.builtin.service:
    name: '{{ nftables_service_name }}'
    state: 'reloaded'
  when:
  - nftables_ansible_reload | bool
  - nftables_state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]

- name: 'Security | NFTables | Restart Service'
  ansible.builtin.service:
    name: '{{ nftables_service_name }}'
    state: 'restarted'
  when:
  - nftables_ansible_restart | bool
  - nftables_state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]
...
