---
- name: 'NFTables | Validate Conf and Reload Service'
  ansible.builtin.command: >
    nft -c -f /etc/nftables.conf
  notify:
  - 'NFTables | Reload Service'
  changed_when: true
  when:
  - nftables__ansible_reload | bool
  - nftables__state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]

- name: 'NFTables | Validate Conf and Restart Service'
  ansible.builtin.command: >
    nft -c -f /etc/nftables.conf
  notify:
  - 'NFTables | Restart Service'
  changed_when: true
  when:
  - nftables__ansible_restart | bool
  - nftables__state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]

- name: 'NFTables | Reload Service'
  ansible.builtin.systemd:
    name: '{{ nftables__service_name }}'
    daemon_reload: true
    state: 'reloaded'
  when:
  - nftables__ansible_reload | bool
  - nftables__state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]

- name: 'NFTables | Restart Service'
  ansible.builtin.systemd:
    name: '{{ nftables__service_name }}'
    daemon_reload: true
    state: 'restarted'
  when:
  - nftables__ansible_restart | bool
  - nftables__state != 'absent'
  - not ansible_check_mode
  tags: [ 'always' ]
...
