---
- name: 'Configure | Delete a OpenSSH Conf File'
  ansible.builtin.file:
    dest: '{{ item.dest | mandatory }}'
    state: 'absent'
  loop: '{{ sshd__conf | selectattr("state", "havlasme.ansible.is_absent") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'OpenSSH | Validate Conf and Reload Service'

- name: 'Configure | Create the OpenSSH Conf Directory Structure'
  ansible.builtin.file:
    dest: '{{ item.dest | mandatory }}'
    owner: '{{ item.user | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode: '{{ item.mode | d("0755") }}'
    state: 'directory'
  loop: '{{ sshd__conf | selectattr("state", "havlasme.ansible.is_directory") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'OpenSSH | Validate Conf and Restart Service'
  tags: [ 'role:sshd', 'role:sshd:configure', 'task:configure' ]

- name: 'Configure | Create and Update a OpenSSH Conf File'
  ansible.builtin.template:
    dest: '{{ item.dest | mandatory }}'
    src: '{{ lookup("havlasme.ansible.template", item.template | d(sshd__conf_template)) }}'
    owner: '{{ item.user | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode: '{{ item.mode | d("0600") }}'
    backup: '{{ item.backup | d(false) }}'
    validate: '{{ "sshd -t -f %s" if (item.validate|d(true)|bool) else omit }}'
  loop: '{{ sshd__conf | selectattr("state", "havlasme.ansible.is_present") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'OpenSSH | Validate Conf and Reload Service'

- name: 'Configure | Check the Available Moduli Size'
  ansible.builtin.shell: >
    awk '$5 < {{ sshd__moduli_minsize }}' '{{ sshd__moduli_file }}'
  when:
  - sshd__moduli_minsize is defined
  register: sshd__moduli_minsize_check
  changed_when: sshd__moduli_minsize_check.stdout
  check_mode: false

- name: 'Configure | Delete the Small Moduli (< {{ sshd__moduli_minsize | d(3071) }})'
  ansible.builtin.shell: >
    awk '$5 >= {{ sshd__moduli_minsize }}' '{{ sshd__moduli_file }}' > '{{ sshd__moduli_file }}.ansible' ;
    [ -r '{{ sshd__moduli_file }}.ansible' -a -s '{{ sshd__moduli_file }}.ansible' ] && mv '{{ sshd__moduli_file }}.ansible' '{{ sshd__moduli_file }}' || rm '{{ sshd__moduli_file }}.ansible'
  notify:
  - 'OpenSSH | Validate Conf and Restart Service'
  when:
  - sshd__moduli_minsize is defined
  - sshd__moduli_minsize_check.stdout
  changed_when: true
...
