---
- name: "security | sshd | set the issue message"
  ansible.builtin.template:
    dest: "{{ sshd__issue_file }}"
    src: "{{ sshd__issue_template }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "security | sshd | reload"
  when:
  - "sshd__issue_template is defined"

- name: "security | sshd | delete "
  ansible.builtin.file:
    dest: "{{ sshd__conf_d }}/{{ item.dest | mandatory }}"
    state: "absent"
  loop: "{{ sshd__conf_d_file | selectattr('state', 'defined') | selectattr('state', 'equalto', 'absent') | list }}"
  notify: "security | sshd | reload"

- name: "security | sshd | configure snippet"
  ansible.builtin.template:
    dest: "{{ sshd__conf_d }}/{{ item.dest | mandatory }}"
    src: "{{ item.src | mandatory }}"
    owner: "root"
    group: "root"
    mode: "0644"
    force: "yes"
    validate: "sshd -t -f %s"
  loop: "{{ sshd__conf_d_file | selectattr('src', 'defined') }}"
  when: "item.state | d('present') == 'present'"
  notify: "security | sshd | reload"

- name: "security | sshd | configure snippet"
  ansible.builtin.copy:
    dest: "{{ sshd__conf_d }}/{{ item.dest | mandatory }}"
    content: "{{ item.content | mandatory }}"
    owner: "root"
    group: "root"
    mode: "0644"
    force: "yes"
    validate: "sshd -t -f %s"
  loop: "{{ sshd__conf_d_file | selectattr('content', 'defined') }}"
  when: "item.state | d('present') == 'present'"
  notify: "security | sshd | reload"

- name: "security | sshd | configure"
  ansible.builtin.template:
    dest: "{{ sshd__conf_file }}"
    src: "{{ sshd__conf_template }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "sshd -t -f %s"
  notify: "security | sshd | reload"
