---
- name: 'Configure | Delete a OpenSSH Conf File'
  ansible.builtin.file:
    dest: '{{ item.dest | mandatory | havlasme.ansible.abspath(sshd_confdir) }}'
    state: 'absent'
  loop: '{{ sshd_conf | selectattr("state", "havlasme.ansible.is_absent") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'OpenSSH | Validate Conf and Reload Service'

- name: 'Configure | Create or Update a OpenSSH Conf File'
  ansible.builtin.template:
    dest: '{{ item.dest | mandatory | havlasme.ansible.abspath(sshd_confdir) }}'
    src: '{{ item.tmpl | d(sshd_conf_template) }}'
    owner: 'root'
    group: 'root'
    mode: '{{ item.mode | d("0600") }}'
    validate: '{{ "sshd -t -f %s" if (item.validate|d(true)|bool) else omit }}'
  loop: '{{ sshd_conf | selectattr("state", "havlasme.ansible.is_present") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'OpenSSH | Validate Conf and Reload Service'

- name: 'Configure | Check the Available Moduli Size'
  ansible.builtin.shell: >
    awk '$5 < {{ sshd_moduli_minsize }}' '{{ sshd_moduli_file }}'
  when:
  - sshd_moduli_minsize is defined
  register: sshd_moduli_minsize_check
  changed_when: sshd_moduli_minsize_check.stdout
  check_mode: false

- name: 'Configure | Delete the Small Moduli (< {{ sshd_moduli_minsize }})'
  ansible.builtin.shell: >
    awk '$5 >= {{ sshd_moduli_minsize }}' '{{ sshd_moduli_file }}' > '{{ sshd_moduli_file }}.ansible' ;
    [ -r '{{ sshd_moduli_file }}.ansible' -a -s '{{ sshd_moduli_file }}.ansible' ] && mv '{{ sshd_moduli_file }}.ansible' '{{ sshd_moduli_file }}' || rm '{{ sshd_moduli_file }}.ansible'
  notify:
  - 'OpenSSH | Validate Conf and Restart Service'
  when:
  - sshd_moduli_minsize_check.stdout
  changed_when: true
...
