---
- name: 'Security | SSHd | Configure | Check Available Moduli Size'
  ansible.builtin.shell: >
    awk '$5 < {{ sshd_moduli_minsize }}' '{{ sshd_moduli_file }}'
  when:
  - sshd_moduli_minsize is defined
  register: sshd_moduli_minsize_check
  changed_when: sshd_moduli_minsize_check.stdout
  check_mode: false

- name: 'Security | SSHd | Configure | Remove Small Moduli'
  ansible.builtin.shell: >
    awk '$5 >= {{ sshd_moduli_minsize }}' '{{ sshd_moduli_file }}' > '{{ sshd_moduli_file }}.ansible' ;
    [ -r '{{ sshd_moduli_file }}.ansible' -a -s '{{ sshd_moduli_file }}.ansible' ] && mv '{{ sshd_moduli_file }}.ansible' '{{ sshd_moduli_file }}' || rm '{{ sshd_moduli_file }}.ansible'
  notify:
  - 'Security | SSHd | Validate Conf and Restart Service'
  when:
  - sshd_moduli_minsize_check.stdout
  changed_when: true

- name: 'Security | SSHd | Configure | Ensure Key Revocation List Exists (to Avoid Lock-Out)'
  ansible.builtin.copy:
    dest: '{{ sshd_key_revocation_list_file }}'
    content: ''
    owner: 'root'
    group: 'root'
    mode: '0600'
    force: false
  notify:
  - 'Security | SSHd | Validate Conf and Reload Service'
  when:
  - sshd_key_revocation_list_file is defined

- name: 'Security | SSHd | Configure | Create or Update Key Revocation List'
  ansible.builtin.template:
    dest: '{{ sshd_key_revocation_list_file }}'
    src: '{{ sshd_key_revocation_list_template }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
  - 'Security | SSHd | Validate Conf and Reload Service'
  when:
  - sshd_key_revocation_list_template is defined

- name: 'Security | SSHd | Configure | Create or Update `issue` File'
  ansible.builtin.template:
    dest: '{{ sshd_issue_file | d("/etc/issue.net") }}'
    src: '{{ sshd_issue_template }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
  - sshd_issue_template is defined

- name: 'Security | SSHd | Configure | Remove Configuration File'
  ansible.builtin.file:
    dest: '{{ item.dest | mandatory | havlasme.security.abspath(sshd_conf_d) }}'
    state: 'absent'
  loop: '{{ sshd_conf | selectattr("state", "havlasme.security.is_absent") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'Security | SSHd | Validate Conf and Reload Service'

- name: 'Security | SSHd | Configure | Create or Update Configuration File'
  ansible.builtin.template:
    dest: '{{ item.dest | mandatory | havlasme.security.abspath(sshd_conf_d) }}'
    src: '{{ item.src | d(sshd_conf_template) }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    validate: sshd -t -f %s
  loop: '{{ sshd_conf | selectattr("state", "havlasme.security.is_present") | list }}'
  loop_control:
    label: '{{ item.dest | mandatory }}'
  notify:
  - 'Security | SSHd | Validate Conf and Reload Service'
...
