---
- name: "security | sshd | configure"
  ansible.builtin.template:
    src: "{{ sshd__conf_tmpl }}"
    dest: "{{ sshd__conf_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
    force: "yes"
  notify: "security | sshd | reload"
