---
- name: "security | sshd | check available moduli size"
  ansible.builtin.shell: > 
    awk '$5 < {{ sshd_moduli_minsize }}' '{{ sshd_moduli_file }}'
  when:
  - "sshd_moduli_minsize is defined"
  changed_when: "sshd_moduli_minsize_check.stdout"
  check_mode: "no"
  register: "sshd_moduli_minsize_check"

- name: "security | sshd | delete small moduli"
  ansible.builtin.shell: >
    awk '$5 >= {{ sshd_moduli_minsize }}' '{{ sshd_moduli_file }}' > '{{ sshd_moduli_file }}.ansible' ;
    [ -r '{{ sshd_moduli_file }}.ansible' -a -s '{{ sshd_moduli_file }}.ansible' ] && mv '{{ sshd_moduli_file }}.ansible' '{{ sshd_moduli_file }}' || rm '{{ sshd_moduli_file }}.ansible'
  when:
  - "sshd_moduli_minsize is defined"
  - "sshd_moduli_minsize_check.stdout"
  notify: "security | sshd | restart service"

- ansible.builtin.import_tasks: "configure/d.yml"

- name: "security | sshd | create or update configuration file"
  ansible.builtin.template:
    dest: "{{ sshd_conf_file }}"
    src: "{{ sshd_conf_template }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "sshd -t -f %s"
  notify: "security | sshd | reload service"
