---
- name: "security | sshd | check sshd moduli size"
  shell: "awk '$5 < {{ sshd_moduli_minimum }}' '{{ sshd_moduli_file }}'"
  changed_when: False
  check_mode: False
  when:
  - "sshd_moduli_minimum is defined"
  register: "sshd_moduli_minimum_check"

- name: "security | sshd | delete small sshd moduli"
  shell: awk '$5 >= {{ sshd_moduli_minimum }}' '{{ sshd_moduli_file }}' > '{{ sshd_moduli_file }}.ansible' ;
    [ -r '{{ sshd_moduli_file }}.ansible' -a -s '{{ sshd_moduli_file }}.ansible' ] && mv '{{ sshd_moduli_file }}.ansible' '{{ sshd_moduli_file }}' || rm '{{ sshd_moduli_file }}.ansible'
  when:
  - "sshd_moduli_minimum is defined"
  - "sshd_moduli_minimum_check.stdout"
  notify: "security | sshd | restart service"

- import_tasks: "configure_d/main.yml"

- name: "security | sshd | create or update the configuration file"
  ansible.builtin.template:
    dest: "{{ sshd_conf_file }}"
    src: "{{ sshd_conf_template }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "sshd -t -f %s"
  notify: "security | sshd | reload service"
