---
- name: "security | sshd | configure"
  ansible.builtin.template:
    dest: "{{ sshd__conf }}"
    src: "{{ sshd__conf_template }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "sshd -t -f %s"
  notify: "security | sshd | reload"
