---
- name: "security | sshd | install"
  ansible.builtin.package:
    name: "{{ sshd__package_name }}"
    state: "{{ sshd__state }}"
  notify: "security | sshd | restart"

- name: "security | sshd | create directory structure"
  ansible.builtin.file:
    name: "{{ item | mandatory }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  loop:
  - "{{ sshd__confdir }}"
  - "{{ sshd__conf_includedir }}"
  notify: "security | sshd | reload"
