---
- name: 'Install | {{ sshd_state | replace("present", "Install") | replace("latest", "Update") }} the OpenSSH via APT'
  ansible.builtin.apt:
    name: '{{ sshd__package_name }}'
    update_cache: true
    cache_valid_time: 1800
    state: '{{ sshd__state }}'
  notify:
  - 'OpenSSH | Validate Conf and Restart Service'
...
