---
- name: "security | sshd | install or update package via apt"
  ansible.builtin.apt:
    name: "{{ sshd_package_name }}"
    state: "{{ sshd_state }}"
  notify: "security | sshd | restart service"

- name: "security | sshd | create a directory structure"
  ansible.builtin.file:
    dest: "{{ item.dest | mandatory }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  loop:
  - { dest: "{{ sshd_conf_file | dirname }}" }
  - { dest: "{{ sshd_conf_d }}" }
  loop_control:
    label: "{{ item.dest | mandatory }}"
  notify: "security | sshd | reload service"
