---
- name: "security | sshd | install via apt"
  ansible.builtin.apt:
    name: "{{ sshd__package_name }}"
    state: "{{ sshd__state }}"
  notify: "security | sshd | restart"

- name: "security | sshd | create directory structure"
  ansible.builtin.file:
    dest: "{{ item.dest | mandatory }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode | d('0755') }}"
    state: "directory"
  loop:
  - { dest: "{{ sshd_conf_file | dirname }}" }
  - { dest: "{{ sshd__conf_d }}", mode: "0700" }
  notify: "security | sshd | reload"
