---
- name: 'security | sshd | install or update package via apt'
  ansible.builtin.apt:
    name: '{{ sshd_package_name }}'
    state: '{{ sshd_state }}'
  notify:
  - 'security | sshd | validate conf and restart service'

- name: 'security | sshd | create directory structure'
  ansible.builtin.file:
    dest: '{{ sshd_conf_d }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  notify:
  - 'security | sshd | validate conf and reload service'
