---
- name: 'Install | Install or Update the OpenSSH via APT'
  ansible.builtin.apt:
    name: '{{ sshd_package_name }}'
    update_cache: true
    state: '{{ sshd_state }}'
  notify:
  - 'OpenSSH | Validate Conf and Restart Service'

- name: 'Install | Create the OpenSSH Conf Directory Structure'
  ansible.builtin.file:
    dest: '{{ sshd_confdir }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  notify:
  - 'OpenSSH | Validate Conf and Reload Service'
...
