---
- name: 'Install | Install or Update the SSHd Package via APT'
  ansible.builtin.apt:
    name: '{{ sshd_package_name }}'
    state: '{{ sshd_state }}'
  notify:
  - 'Security | SSHd | Validate Conf and Restart Service'

- name: 'Install | Create the SSHd Conf Directory Structure'
  ansible.builtin.file:
    dest: '{{ sshd_conf_d }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  notify:
  - 'Security | SSHd | Validate Conf and Reload Service'
...
