---
- name: 'Assert that the OpenSSH State Value is Valid'
  ansible.builtin.assert:
    that:
    - sshd__state in [ 'present', 'latest' ]
    msg: 'The sshd__state must be one of [ "present", "latest" ] - "{{ sshd__state }}" is not supported'
    quiet: true
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role:sshd', 'role:sshd:install', 'task:install' ]
- ansible.builtin.import_tasks: 'configure.yml'
  tags: [ 'role:sshd', 'role:sshd:configure', 'task:configure' ]
- ansible.builtin.import_tasks: 'service.yml'
  tags: [ 'role:sshd', 'role:sshd:service', 'task:service' ]
...
