---
- name: "security | sshd | include distribution-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: ["always"]

- import_tasks: "install.yml"
  tags: ["role::sshd", "task::install"]
- import_tasks: "configure_d/key_revocation_list.yml"
  tags: [ "role::sshd", "task::configure" ]
- import_tasks: "configure_d/print_issue.yml"
  tags: [ "role::sshd", "task::configure" ]
- import_tasks: "configure.yml"
  tags: ["role::sshd", "task::configure"]
- import_tasks: "service.yml"
  tags: ["role::sshd", "task::service"]
