---
- name: 'Security | SSHd | Include Distribution-Specific Variables'
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'
  tags: [ 'always' ]

- ansible.builtin.import_tasks: 'install.yml'
  tags: [ 'role::sshd', 'task::install', 'role::sshd:install' ]
- ansible.builtin.import_tasks: 'configure.yml'
  tags: [ 'role::sshd', 'task::configure', 'role::sshd:configure' ]
- ansible.builtin.import_tasks: 'service.yml'
  tags: [ 'role::sshd', 'task::service', 'role::sshd:service' ]
...
