---
- name: 'Assert that the Managed Node OS is Supported'
  ansible.builtin.assert:
    that:
    - (ansible_distribution|lower == "debian" and ansible_distribution_version|int in [10, 11, 12]) or
      (ansible_distribution|lower == "ubuntu" and ansible_distribution_version|int in [20, 22, 24])
    msg: 'The "{{ ansible_distribution }} {{ ansible_distribution_version }}" is not supported'
    quiet: true

- name: 'Assert that the Managed Node is Using systemd'
  ansible.builtin.assert:
    that:
    - ansible_service_mgr == 'systemd'
    msg: 'The "{{ ansible_service_mgr }}" init system is not supported'
    quiet: true

- name: 'Assert that the SSHd State Value is Valid'
  ansible.builtin.assert:
    that:
    - sshd_state in [ 'present', 'latest' ]
    msg: 'The sshd_state must be in [ "present", "latest" ]'
    quiet: true
...
