---
- name: 'Service | Start and Enable the OpenSSH Service'
  ansible.builtin.systemd:
    name: '{{ sshd_service_name }}'
    daemon_reload: true
    enabled: '{{ sshd_enabled }}'
    state: 'started'
...
